/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PesananRouteImport } from './routes/pesanan'
import { Route as NotifikasiRouteImport } from './routes/notifikasi'
import { Route as FavoritRouteImport } from './routes/favorit'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CariRouteImport } from './routes/cari'
import { Route as AlamatRouteImport } from './routes/alamat'
import { Route as AkunRouteImport } from './routes/akun'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const PesananRoute = PesananRouteImport.update({
  id: '/pesanan',
  path: '/pesanan',
  getParentRoute: () => rootRouteImport,
} as any)
const NotifikasiRoute = NotifikasiRouteImport.update({
  id: '/notifikasi',
  path: '/notifikasi',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritRoute = FavoritRouteImport.update({
  id: '/favorit',
  path: '/favorit',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CariRoute = CariRouteImport.update({
  id: '/cari',
  path: '/cari',
  getParentRoute: () => rootRouteImport,
} as any)
const AlamatRoute = AlamatRouteImport.update({
  id: '/alamat',
  path: '/alamat',
  getParentRoute: () => rootRouteImport,
} as any)
const AkunRoute = AkunRouteImport.update({
  id: '/akun',
  path: '/akun',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/akun': typeof AkunRoute
  '/alamat': typeof AlamatRoute
  '/cari': typeof CariRoute
  '/checkout': typeof CheckoutRoute
  '/favorit': typeof FavoritRoute
  '/notifikasi': typeof NotifikasiRoute
  '/pesanan': typeof PesananRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/akun': typeof AkunRoute
  '/alamat': typeof AlamatRoute
  '/cari': typeof CariRoute
  '/checkout': typeof CheckoutRoute
  '/favorit': typeof FavoritRoute
  '/notifikasi': typeof NotifikasiRoute
  '/pesanan': typeof PesananRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/akun': typeof AkunRoute
  '/alamat': typeof AlamatRoute
  '/cari': typeof CariRoute
  '/checkout': typeof CheckoutRoute
  '/favorit': typeof FavoritRoute
  '/notifikasi': typeof NotifikasiRoute
  '/pesanan': typeof PesananRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/akun'
    | '/alamat'
    | '/cari'
    | '/checkout'
    | '/favorit'
    | '/notifikasi'
    | '/pesanan'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/akun'
    | '/alamat'
    | '/cari'
    | '/checkout'
    | '/favorit'
    | '/notifikasi'
    | '/pesanan'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/akun'
    | '/alamat'
    | '/cari'
    | '/checkout'
    | '/favorit'
    | '/notifikasi'
    | '/pesanan'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AkunRoute: typeof AkunRoute
  AlamatRoute: typeof AlamatRoute
  CariRoute: typeof CariRoute
  CheckoutRoute: typeof CheckoutRoute
  FavoritRoute: typeof FavoritRoute
  NotifikasiRoute: typeof NotifikasiRoute
  PesananRoute: typeof PesananRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pesanan': {
      id: '/pesanan'
      path: '/pesanan'
      fullPath: '/pesanan'
      preLoaderRoute: typeof PesananRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifikasi': {
      id: '/notifikasi'
      path: '/notifikasi'
      fullPath: '/notifikasi'
      preLoaderRoute: typeof NotifikasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorit': {
      id: '/favorit'
      path: '/favorit'
      fullPath: '/favorit'
      preLoaderRoute: typeof FavoritRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cari': {
      id: '/cari'
      path: '/cari'
      fullPath: '/cari'
      preLoaderRoute: typeof CariRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alamat': {
      id: '/alamat'
      path: '/alamat'
      fullPath: '/alamat'
      preLoaderRoute: typeof AlamatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/akun': {
      id: '/akun'
      path: '/akun'
      fullPath: '/akun'
      preLoaderRoute: typeof AkunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AkunRoute: AkunRoute,
  AlamatRoute: AlamatRoute,
  CariRoute: CariRoute,
  CheckoutRoute: CheckoutRoute,
  FavoritRoute: FavoritRoute,
  NotifikasiRoute: NotifikasiRoute,
  PesananRoute: PesananRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
